apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiteria-bot
  namespace: default
  labels:
    app: quiteria-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiteria-bot
  template:
    metadata:
      labels:
        app: quiteria-bot
    spec:
      containers:
        - name: quiteria-bot
          image: ghcr.io/quickick-has/quiteria-bot:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          envFrom:
            - secretRef:
                name: quiteria-bot-secrets
      # Credenciais para puxar imagens do GitHub Container Registry privado
      imagePullSecrets:
        - name: ghcr-secret
